### ISSUE TITLE
exclude bbp-admin-links

### ISSUE THREAD

**Issue by yet-another-username** [r-a-y/bbp-quote#1]
Hi,

your plugin is very promising and a good alternative to others, which bring a lot of not needed other features.
There is one little bit blocking me from using it on my website. Might it be possible to exclude "bbp-admin-links" and the revision log form the quotes??

thanks in advance,

hannes;

**Comment by r-a-y** [comment]
I fixed an issue with the revision log showing up in the quote in commit 8aa3d82.

As for the `bbp-admin-links` container showing up, I'm guessing you're probably using a custom template that has moved some elements around.  If that is the case, you should maybe move the admin links outside the `bbp-reply-content` container, if possible.
